pub fn get_item(mut number: usize, show_items: bool) -> &'static str {
    let item_list: [&str; 128] = ["Medical Herb",
	"Healing Seed",
	"Healing Drop",
	"Antidote",
	"Angel Wing",
	"Fairy Powder",
	"Healing Water",
	"Fairy Tear",
	"Healing Rain",
	"Power Water",
	"Protect Milk",
	"Quick Chicken",
	"Running Pemento",
	"Chearful Bread",
	"Bright Honey",
	"Brave Apple",
	"Shining Ball",
	"Blizard",
	"Holy Thunder",
	"Power Ring",
	"Protect Ring",
	"Quick Ring",
	"Running Ring",
	"White Ring",
	"Black Ring",
	"Evil Ring",
	"Leather Glove",
	"Power Glove",
	"Brass Knuckles",
	"Iron Knuckles",
	"Misty Knuckles",
	"Giant Knuckles",
	"Evil Knuckles",
	"Short Axe",
	"Hand Axe",
	"Middle Axe",
	"Power Axe",
	"Battle Axe",
	"Large Axe",
	"Great Axe",
	"Heat Axe",
	"Atlas Axe",
	"Ground Axe",
	"Rune Axe",
	"Evil Axe",
	"Wooden Arrow",
	"Iron Arrow",
	"Steel Arrow",
	"Robin Arrow",
	"Assult Shell",
	"Great Shot",
	"Nazca Cannon",
	"Buster Shot",
	"Hyper Cannon",
	"Grand Cannon",
	"Evil Shot",
	"Wooden Stick???????",
	"Short Sword",
	"Middle Sword",
	"Long Sword",
	"Middle Sword",
	"Achiles Sword",
	"Broad Sword",
	"Buster Sword",
	"Great Sword",
	"Critical Sword",
	"Battle Sword",
	"Force Sword",
	"Counter Sword",
	"Levanter",
	"Dark Sword",
	"Wooden Sword",
	"Short Spear",
	"Bronze Lance",
	"Spear",
	"Steel Lance",
	"Power Spear",
	"Heavy Lance",
	"Javelin",
	"Chrome Lance",
	"Valkyrie",
	"Holy Lance",
	"Mist Javelin",
	"Halberd",
	"Evil Lance",
	"Wooden Rod",
	"Short Rod",
	"Bronze Rod",
	"Iron Rod",
	"Power Stick",
	"Flail",
	"Guardian Staff",
	"Indra Staff",
	"Mage Staff",
	"Wish Staff",
	"Great Rod",
	"Supply Staff",
	"Holy Staff",
	"Freeze Staff",
	"Godess Staff",
	"Mystery Staff",
	"Demon Rod",
	"Iron Ball",
	"Short Knife",
	"Dagger",
	"Knife",
	"Theive's Dagger",
	"Kitana",
	"Ninja Kitana",
	"Gisarme",
	"Taros Sword",
	"Right of Hope",
	"Wooden Pannel",
	"Sky Orb",
	"Cannon",
	"Dry Stone",
	"Dynamite",
	"Arm of Golem",
	"Pegasus Wing",
	"Warrior's Pride",
	"Silver Tank",
	"Seceret Book",
	"Vigor Ball",
	"Mithryl",
	"Life Ring??????",
	"Cotton Baloon",
	"Chirrup Sandles",
	"Blank Space"];

    if show_items {
       for i in 0..128 {
         println!("{}: {}", item_list[i as usize], i);
       }
       return ""
    }

    while number > 128 {
    	  number -= 128;
    }

    if number < 128 {
       return item_list[number]
    }
    return ""
}
